# --- !Ups

CREATE TABLE projects (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) UNIQUE,
  date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE artifacts (
  id VARCHAR(64) PRIMARY KEY,
  project_id INT NOT NULL REFERENCES projects(id),
  version VARCHAR(128) UNIQUE,
  date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_internal TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deploys (
  id SERIAL PRIMARY KEY,
  device VARCHAR(64),
  artifact_id VARCHAR(64) NOT NULL REFERENCES artifacts(id),
  date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_internal TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

# --- !Downs

DROP TABLE deploys;
DROP TABLE artifacts;
DROP TABLE projects;
